# Uncomment this line to define a global platform for your project
 platform :ios, '9.0'

target 'FISFlashyTableviews' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for FISFlashyTableviews


pod 'SWTableViewCell', '~> 0.3.7'
pod 'APParallaxHeader'

end
